[tool.poetry]
name = "from-scratch"
version = "0.1.0"
description = "Various NLP, DL techniques and methods implemented from scratch"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
torch = "^2.2.2"
einops = "^0.7.0"
jupyter = "^1.0.0"
matplotlib = "^3.8.4"
pandas = "^2.2.2"
transformers = "^4.39.3"
datasets = "^2.18.0"
accelerate = "^0.29.2"
lightning = "^2.2.1"
wandb = "^0.16.6"
tensorboard = "^2.16.2"
scikit-image = "^0.23.1"
scikit-learn = "^1.4.2"


[tool.poetry.group.dev.dependencies]
autopep8 = "^2.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
