[project]
name = "from-scratch"
version = "0.1.0"
description = "implementation of machine learning concepts from scratch"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.4.0",
    "altair>=5.5.0",
    "datasets>=3.3.2",
    "einops>=0.8.1",
    "ipython>=8.32.0",
    "jupyter>=1.1.1",
    "lightning>=2.5.0.post0",
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "tensorboard>=2.19.0",
    "torch>=2.6.0",
    "torchaudio>=2.6.0",
    "torchvision>=0.21.0",
    "transformers>=4.49.0",
    "wandb>=0.19.6",
]

[dependency-groups]
dev = [
    "ruff>=0.9.7",
]
