[tool.poetry]
name = "from-scratch"
version = "0.1.0"
description = ""
authors = ["Shawon Ashraf"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.2.2"
jupyter = "^1.1.1"
matplotlib = "^3.10.0"
pandas = "^2.2.3"
scikit-learn = "^1.6.1"
wandb = "^0.19.5"
tensorboard = "^2.18.0"
altair = "^5.5.0"


[tool.poetry.group.dev.dependencies]
ruff = "^0.9.4"

[tool.poetry.group.intelmac]
optional = true

[tool.poetry.group.intelmac.dependencies]
torch = ">=2.2.0"
torchaudio = ">=2.2.0"
torchvision = ">=0.17"
lightning = "^2.5.0.post0"



[tool.poetry.group.linux]
optional = true

[tool.poetry.group.linux.dependencies]
torch = "^2.6.0"
torchaudio = "^2.6.0"
torchvision = "^0.21"
accelerate = "^1.3.0"
transformers = "^4.48.2"
einops = "^0.8.0"
datasets = "^3.2.0"
lightning = "^2.5.0.post0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
